title: "Paulo Leonardo Benatto [patito]"
#url: "patito.github.com"
author: "Paulo Leonardo Benatto"
email: "benatto@gmail.com"
description: "Blog pessoal de Paulo Leonardo Benatto (patito)."

auto: false
source: .
paginate: 5
paginate_files:
 - index.html

permalink: /:year/:month/:title

markdown: rdiscount
pygments: true

exclude:
  - README.markdown
  - _drafts
