title: "pedrovitti"
author: "Pedro Vitti"
email: "pedrovitti@gmail.com"
description: "Pedro Vitti personal website."
url: .
source: .
permalink: /:year/:month/:title

markdown: rdiscount
pygments: true

exclude:
  - README.markdown
  - _drafts
