title: "pedrovitti"
#url: "patito.github.com"
author: "Pedro Vitti"
email: "pedrovitti@gmail.com"
description: "Pedro Vitti personal website."

source: .
permalink: /:year/:month/:title

markdown: rdiscount
pygments: true

exclude:
  - README.markdown
  - _drafts
