title: "malelficus"
#url: "patito.github.com"
author: "malelficus project"
email: "maleficus@gmail.com"
description: "Documentation of malelficus project."

source: .
permalink: /:year/:month/:title

markdown: rdiscount
pygments: true

exclude:
  - README.markdown
  - _drafts
